kind: Deployment
apiVersion: apps/v1
metadata:
  name: profiling-app
  labels:
    app: profiling-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profiling-app
  template:
    metadata:
      labels:
        app: profiling-app
    spec:
      containers:
        - name: profiling-app
          image: default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/qaylasyadzaa-dev/starlight-gue:3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: transaction-app-secret
                  key: MONGODB_URI
            - name: MONGODB_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: transaction-app-config
                  key: MONGODB_DB_NAME
