kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-container
  labels:
    app: my-container
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-container
  template:
    metadata:
      labels:
        app: my-container
    spec:
      containers:
        - name: my-container
          image: default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/qaylasyadzaa-dev/aplikasi-gue:3.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: transaction-app-secret
                  key: MONGODB_URI
            - name: MONGODB_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: transaction-app-config
                  key: MONGODB_DB_NAME
